### ISSUE TITLE
Ahren Bonnema - SpoonMe thoughts

### ISSUE THREAD

**Issue by abonnema143** [spoonme-kitchen/spoonme-public#1]
- I wish there was a space to enter active calories burned for the day

1. I workout 5-6 days/week and my active calorie burn varies quite a bit
2. On rest days it's important I restrict more or hit my daily target
3. I typically do at least 1 workout that burns over 1000 calories (sometimes up to 2000) 
4. Its equally important I get enough extra calories on those days for recovery but still need to be careful that I don't go hog wild and blow way past my goal. 

- When searching for food items I've found the library of options not comprehensive (not sure how it could be)
1. It's honestly better than the dumpster fire of user generated items in FoodVisor
5. I am able to find what I am looking for much more quickly than foodvisor
6. It's easier to edit the portions quickly (love this) 

- Overall appreciate the cleanliness and minimalism so far
- I don't see a change in my overall calorie count when I modify my macros or vice versa like I do in food visor

**Comment by mattcantstop** [comment]
> It's honestly better than the dumpster fire of user generated items in FoodVisor

@abonnema143, completely agree about this. This is something that @migarjo is actively working on. We are going to hire moderators to improve the data as well. Our goal is that it is the best database around. We have a plan to make it happen. 

One thing we are considering is having categories of food to make filtering a bit easier. Something we have talked about.

**Comment by mattcantstop** [comment]
> I don't see a change in my overall calorie count when I modify my macros or vice versa like I do in food visor

Can you give a bit more detail about this? CC: @TheArrowsmith

**Comment by migarjo** [comment]
HI @abonnema143, thanks for the feedback! I'm working primarily on making Foods list as complete and easy to use as possible. In that vein, you mentioned that the food list is not comprehensive. In a situation where you do not find a food, we do have the "+ Add custom entry" option. If for any reason you don't want to use it, you certainly don't have to, but I plan on using entries from there to identify gaps in our database. With that said I have a couple of questions:

- Was the "+ Add custom entry" option clear to you as you started entering foods?
- Is it a feature you're interested in using?

**Comment by abonnema143** [comment]
Hi @migarjo, I totally missed this. I admittedly have been rushing as I've been using the app. This is super, I'll start making custom entries. Thanks!

**Comment by abonnema143** [comment]
> > I don't see a change in my overall calorie count when I modify my macros or vice versa like I do in food visor
> 
> Can you give a bit more detail about this? CC: @TheArrowsmith

In Foodvisor when I make tweaks to my macro calories (Protein, Carbs, Fat) It automatically adjusts my total calorie count to reflect these changes as I make them. I honestly don't know how accurate or important this is. But it feels nice to watch my calorie count go up and down in real time as I try to figure out the balance of macros. It also keeps me accountable. "Oh crap, moving my fats goal up to 100g puts me way over my total goal, I'd better take it down a bit!"

**Comment by migarjo** [comment]
> I totally missed this. I admittedly have been rushing as I've been using the app. This is super, I'll start making custom entries. 

This is great feedback for us! It may mean that we need to make the option to create custom entries more obvious, or a more integrated part of adding ingredients. Thanks!

**Comment by TheArrowsmith** [comment]
> In Foodvisor when I make tweaks to my macro calories (Protein, Carbs, Fat) It automatically adjusts my total calorie count to reflect these changes as I make them. 

Just to be clear, by "total calories" do you mean the daily totals/targets that are visible on the journal page?

<img width="838" alt="image" src="https://github.com/PeakStreak/spoonme-public/assets/85154056/9e960499-749f-430d-822a-895019661519">

So you're saying that it would be good to see these get adjusted in real time as you add/adjust a new journal entry?

That makes sense. I'll add it to the list.

**Comment by abonnema143** [comment]
![Screenshot_20240118_162410](https://github.com/PeakStreak/spoonme-public/assets/156356945/77a8d1bd-2cb3-4fff-a849-74da7c808f50)
![Screenshot_20240118_162437_Chrome](https://github.com/PeakStreak/spoonme-public/assets/156356945/8d32b6dc-29d5-45d7-9725-8a6737bc2554)

**Comment by abonnema143** [comment]
Apologies for the late reply. I'm referring to the page where I customize my macro calories that I believe should roll up to my total calorie daily goal.

**Comment by abonnema143** [comment]
For example in foodvisor when I change my protein from 160g/day to 110g/day my total calorie count for the day shows a real time reduction to reflect this before I hit the save button

**Comment by migarjo** [comment]
Thanks again for the feedback, @abonnema143! I've compiled the remaining open issues you brought up here in some tracking issues, so I'm going to close this for now. Feel free to reopen this or open another issue if you want to keep discussing for any reason.
