### ISSUE TITLE
Search for food by source and title

### ISSUE THREAD

**Issue by nelsonwittwer** [spoonme-kitchen/spoonme-public#11]
I got a chili from Costco that I wanted to track. I searched for “chili” and saw lots of entries. I tried giving more context “Costco chili” hoping to see an entry there since I’d seen Costco items in other searches. It didn’t appear to let me search by that dimension in the app. 

When I’ve worked with ElasticSearch in the past, you can assign a boost value for a specific field of your search document where you assign higher matches for title but lower matches for another field - in this case source- so you can search both dimensions with one input. Not sure if your tech lets you do something similar or not but that’s how I’ve implemented that in the past. 

It’s also possible there isn’t an entry for Costco chili in which you can ignore what I’m saying :)

**Comment by migarjo** [comment]
Hi @nelsonwittwer,

Our search does include both the brand name and food name fields, but we don't have Costco Chili. I just checked our database, and we actually only have 3 Costco-branded foods. We do, however, have about 170 Kirkland Signature foods, but we don't have chili there either 😄. This brings up something else we will want to include eventually: One way or another, we will want to add intelligence that can alias brands with associated stores. This is great, thanks for bringing this up, and please keep the feedback coming!

**Comment by TheArrowsmith** [comment]
Since the original suggestion (that we allow for searching by brand name) is already implemented, I'll mark this issue closed.

@migarjo will keep working on improving our database to make sure we include Costco chili and all the other foods we're still missing.
