### ISSUE TITLE
Custom ingredients not populating in search

### ISSUE THREAD

**Issue by abonnema143** [spoonme-kitchen/spoonme-public#12]
I created a custom ingredient 'Coach's Oats - Whole Grain Oatmeal' in my daily journal
When I tried to search for this to add to another journal or when creating a new recipe it does not show up.
I'm assuming you may be moderating user generated entries to avoid the dumpster fire database common on other apps. 
I wonder if it would be possible to keep a separate user database that only I can see. That way if something isn't in the database I don't have to re-enter all the data every time I use it but it wouldn't poison the well.

**Comment by abonnema143** [comment]
Screenshots
<img width="1075" alt="Screenshot 2024-01-19 at 8 40 38 AM" src="https://github.com/PeakStreak/spoonme-public/assets/156356945/d1ef69da-3d20-4b70-b4ea-a751dd0fe43d">
<img width="1216" alt="Screenshot 2024-01-19 at 8 40 14 AM" src="https://github.com/PeakStreak/spoonme-public/assets/156356945/e7c3e85f-f08c-4b8c-9483-b59c5fbefe04">
<img width="1216" alt="Screenshot 2024-01-19 at 8 39 57 AM" src="https://github.com/PeakStreak/spoonme-public/assets/156356945/3058e9ae-783d-4bd2-b3f4-7f2b7f9c72e9">

**Comment by migarjo** [comment]
Hi @abonnema143,

Sorry for the slow response here, and thanks for bringing this up! Currently, when you add a custom food to the Journal, it is only logged as a one-off, and isn't saved for future use. Adding the ability to save foods for future use in both Recipes and the Journal is something we're currently designing. This is subject to change, but right now we envision an ability to create foods that only you see, with a minimum of a few fields you would need to add (i.e. Name, Calories). We want to eventually enhance this further to where super users could propose that their food be saved to our public food database. This requires a lot more data (e.g. portion sizes, carbs, protein, fat), so we'll provide another form for you to fill out if you wanted to take your foods to the next step.

Both the basic food adding and the public food application will take some thought and design, but we're also adding a quick intermediate fix, which is a "Recently Added" section to the Journal search results. This won't allow you to add those custom foods as recipe ingredients, but it should at least allow you to re-add custom foods in the Journal, as long as you have used them recently enough. We'll keep you updated as we add the User Foods functionality!

**Comment by TheArrowsmith** [comment]
> we're also adding a quick intermediate fix, which is a "Recently Added" section to the Journal search results.

Just to clarify, there's already a way to re-add a 'custom entry' that you've already tracked, by opening the menu for that entry in the journal screen and clicking "Track again":

<img width="886" alt="Screenshot 2024-02-05 at 19 49 56" src="https://github.com/PeakStreak/spoonme-public/assets/85154056/2be2c526-f675-4d3b-8bed-1bf5e49a58c0">

The upcoming "recently tracked" tab on the journal search page is just an alternative (and hopefully more convenient) UI for the same effect.

Other than that, +1 to everything @migarjo said.

**Comment by migarjo** [comment]
@abonnema143, I've added your request to have a list of foods only you can see to a separate tracking issue. I'll close this for now. Thanks again for the feedback!
