### ISSUE TITLE
Restraunt menu items

### ISSUE THREAD

**Issue by abonnema143** [spoonme-kitchen/spoonme-public#14]
Tried to add Domino's pizza slice I ate. Seemed like only frozen grocery options. Any plans to add menu items from popular chain restaurants?

**Comment by mattcantstop** [comment]
@abonnema143, yes, we do plan on adding this. We plan on making it so users can add these things (with a mechanism to make them high quality and curated) and we plan on going through the top 50 or so restaurants in the USA and adding their menu items. This is definitely in the plans.

**Comment by migarjo** [comment]
@abonnema143, I'm going to close this issue for now, since this is consistent with our future plans and it's only a matter of timing. Thanks for the feedback!
