### ISSUE TITLE
Adding Recipe to Journal

### ISSUE THREAD

**Issue by bkilshaw** [spoonme-kitchen/spoonme-public#15]
I made a recipe called "Yogurt" but when I search for it I can't find it since there's so many other Yogurt entries. One possible solution would be to order the search results so that your recipes are at the top of the results? It would also be awesome to see the "creators name" in the search results to help differentiate.

**Comment by mattcantstop** [comment]
@bkilshaw this is something we are working on in our current priorities. @migarjo and I were evaluating how to best show results. We should be releasing something in the near term on this. Completely agree with you.

**Comment by migarjo** [comment]
@bkilshaw,

We've now shipped an update that puts your recipes at the top of the search results! I'll close this issue as a result.

<img width="300" alt="image" src="https://github.com/PeakStreak/spoonme-public/assets/11798972/7c6cdd00-9542-42fb-a19d-52ae7259820b">
