### ISSUE TITLE
Goals Calculations

### ISSUE THREAD

**Issue by bkilshaw** [spoonme-kitchen/spoonme-public#16]
A couple idea's around goal calculations:

Currently I can enter whatever goals I want, even if the numbers don't add up. There's nothing stopping me from saying I want to eat 2500 calories, but also 9,000 grams of fat (81,000 calories). It would e nice if each field updated to reflect the changes in other fields

If you update your calories it could update your macros to maintain the same ratio's they currently have. Example:
```
Calories: 340
Protein:  30g  (50% of total calories)
Fat:      20g  (33% of total calories)
Carbs:    10g  (17% of total calories)
```
If you update your calories to 680 it would update the macros:
```
Calories: 680
Protein:  60g  (50% of total calories)
Fat:      40g  (33% of total calories)
Carbs:    20g  (17% of total calories)
```

However if I update my macro's it would instead update the total calories
```
Calories: 840
Protein:  100g (63% of total calories)
Fat:      40g  (25% of total calories)
Carbs:    20g  (13% of total calories)
```

Alternatively you could build out a slightly complicated goal calculator that give you the option to set each macro to be a specific percentage of your diet and then let the macro's work themselves out based on your calorie goal.

**Comment by mattcantstop** [comment]
@bkilshaw this is great feedback, and I agree. We were going with very simple for this first version of the onboarding calculator. But these would be great improvements in the future. We will refer to this during the next iteration.

**Comment by migarjo** [comment]
@bkilshaw, I've added this request to a tracking issue that groups it with similar requests from other users. As a result, I'm closing this for now. If you want to discuss this further, please feel free to re-open this issue. Thanks again for the feedback!
