### ISSUE TITLE
Feedback for creating a new recipe

### ISSUE THREAD

**Issue by a-a-ron** [spoonme-kitchen/spoonme-public#2]
Hey there! I was going through the option to create a new recipe and I ran into some issues. Please see the below for more information.

---

**Adding a new ingredient does not allow for measuring cup fractions**

A common ingredient for recipes are fractions of a measuring cup (1/2, 3/4, etc.) I get an invalid response when trying to use fractions. I guess I could convert those fractions to ounces for fluids or grams for solids but that makes the experience a bit cumbersome. 

![Image](https://github.com/PeakStreak/spoonme-public/assets/6351798/0536ddf3-de69-4630-a169-4eee933e232f)

**Ingredient box is hard to work with**

When inputing the directions, working in the small box is hard. When I expand the box, the box will randomly shrink back to the smaller size while typing. If I hit return while typing, the box also shrinks back to the smaller size. I also can't use standard markdown which would be nice to bold text and use headers. 

![Image](https://github.com/PeakStreak/spoonme-public/assets/6351798/45e4fa3b-17b4-40ca-a19b-b8062ce11388)

**Some ingredients don't have the necessary options**

When searching for some ingredients, like dijon mustard, I couldn't find one that had tablespoon as an option. They only had servings, grams, and ounces. I didn't try all of them since there were about 30 different options for dijon mustard but the random 4 I tried all showed the same

![Image](https://github.com/PeakStreak/spoonme-public/assets/6351798/10162875-635c-49d4-b833-23ed6f6f47f5)

**Comment by mattcantstop** [comment]
> A common ingredient for recipes are fractions of a measuring cup (1/2, 3/4, etc.) I get an invalid response when trying to use fractions. I guess I could convert those fractions to ounces for fluids or grams for solids but that makes the experience a bit cumbersome.

@a-a-ron, @migarjo brought this up in a meeting this week. We are going to address this. CC: @TheArrowsmith 

> When searching for some ingredients, like dijon mustard, I couldn't find one that had tablespoon as an option. They only had servings, grams, and ounces.

Great catch. We have discussed this as well, and need to remedy it. The amount of ways people measure things worldwide is absolutely dizzying, but for a US based company, we need to have these measurements, I agree.

**Comment by TheArrowsmith** [comment]
We do need a better way to add fractions. In the meantime you can work around the problem by inputting the fractions as decimals e.g. `0.5` instead of 1/2.

Dijon mustard not having tablespoons is a data issue - we're working hard to make our food database as comprehensive and accurate as possible but with ~400k foods (and counting), not everything is going to be perfect at this early stage. I'll add this to the list of foods we need to review. We'd probably also benefit from having some kind of "report" button where users can flag data issues to us.

If you're wondering why we can't just blanket add "tablespoons" as a possible measurement for _every_ food, the answer is that we don't necessarily have the nutritional data - we might know how many calories etc. are in a _gram_ of dijon mustard, but our database doesn't know how many grams are in a tablespoon. That's not to say we can't figure it out and add it, but again, it's going to take a while to find and fix every such piece of missing data.

In the meantime please let us know about any other issues you find - your feedback is greatly appreciated!

**Comment by mattcantstop** [comment]
@a-a-ron, to give some more details on this, we are building out `Spoonme Certified` ingredients. Those 4,000 ingredients or so will meet a certain level of quality in terms of their titles, description, default units, nutritional facts, images of those ingredients, etc. We are working on that, but I'll take some time. @migarjo is point person on that initiative. 

> Ingredient box is hard to work with

@TheArrowsmith, if I remember correctly rails had a text area, vs a text field. Can we change the defaults there to make it larger out of the box? I am not sure about the issue @a-a-ron is seeing where it will `"shrink back to the smaller size while typing"`, we can look at that separately.

**Comment by a-a-ron** [comment]
Here's a short demo of me using the description box if that helps. It seems to snap back to the original small size each time I enlarge the box and start typing or when I hit return. 

I love the work so far! I'm excited to start using it more when it gets dialed. 

https://github.com/PeakStreak/spoonme-public/assets/6351798/9cc4e434-5536-40f9-bfe4-0c699557b843

**Comment by TheArrowsmith** [comment]
Hi @a-a-ron , this issue with the instructions input undoing the resize is now fixed. Thanks for letting us know!

**Comment by TheArrowsmith** [comment]
Oh and I forgot to mention, I also increased the default height of the input:

<img width="867" alt="image" src="https://github.com/PeakStreak/spoonme-public/assets/85154056/dcfc2076-540f-43c6-94a5-979a9e148244">

**Comment by migarjo** [comment]
> When searching for some ingredients, like dijon mustard, I couldn't find one that had tablespoon as an option. They only had servings, grams, and ounces.

@a-a-ron, We were able to improve this _a bit_ based on your comment thank you! In particular, Dijon Mustard should have volume measurements now if you want to try and enter that again.

**Comment by migarjo** [comment]
Thanks again for the feedback, @a-a-ron ! I added your feedback regarding fraction quantities in a separate tracking issue, so I'm going to close this for now. Feel free to reopen this or open another issue if you want to keep discussing for any reason.
