### ISSUE TITLE
Nutrition Info discrepancy / Entering ingredient portions

### ISSUE THREAD

**Issue by abonnema143** [spoonme-kitchen/spoonme-public#3]
I was adding my granola this morning and notice a discrepancy between the nutrition info in the app vs. what is printed on the package. See attached images
![Screenshot_20240112_083830_Chrome](https://github.com/PeakStreak/spoonme-public/assets/156356945/8cb4e586-e341-4ba2-abe8-847e2b82fa43)
![20240112_083840](https://github.com/PeakStreak/spoonme-public/assets/156356945/e3a16f67-3ac0-430a-bc64-aaa309bb7523)

Also, I was adding blueberries and noticed I was unable to add fractions of a cup. 1 cup is the only option. If I try to add .25 cup I get an error. Minor annoyance I could always just weigh it on the scale but I figure measuring cups may be more common. See image. 
![Blueberries](https://github.com/PeakStreak/spoonme-public/assets/156356945/20eb2971-bd29-438f-ab7d-37f873b1d8ab)

**Comment by migarjo** [comment]
Thanks for pointing these out, @abonnema143. The ".25" entry not working is a bug we'll definitely need to fix, because you should be able to enter it that way. Just to unblock you for now, the reason for the error is that field requires a leading zero before the decimal point for values less than 1. (i.e. "0.25").

**Comment by TheArrowsmith** [comment]
Hi @abonnema143,

The quantity input issue is fixed now - you can add e.g. `.25` as a quantity and it'll accept it.

**Comment by migarjo** [comment]
Hi @abonnema143, 
I updated the serving size on the Love Crunch, and with that I think we've addressed these requests so I'll close this issue.
