### ISSUE TITLE
Recipe fraction tracking in Journal

### ISSUE THREAD

**Issue by colecrawford23** [spoonme-kitchen/spoonme-public#4]
I created two recipes today, both of which I will split up into multiple meals to eat over the course of the week.

I'm not seeing a way to add a portion of that prepped food into the journal for the day. All I'm able to do is add the entire recipe.

I prep a good amount of my meals so being able to toss all of the food into a recipe and then in the journal entry select a fraction of the recipe to track for that day the recipe tool would be more useful.

**Comment by colecrawford23** [comment]
I would prefer if what was added to the journal was inline with the serving size that I created. On the "Simple Frittata" recipe I used 5 as the serving size which will be the number of meals I split that recipe into. It would be helpful if a serving size was added instead of the full recipe.

I love eggs, but don't usually eat 18 all at once ;)

**Comment by mattcantstop** [comment]
> I'm not seeing a way to add a portion of that prepped food into the journal for the day. All I'm able to do is add the entire recipe.

@colecrawford23, thanks for the feedback. This is something we have chatted about internally and we agree this functionality is necessary. @TheArrowsmith is working on this and seeing how we want to implement it, but this is definitely something we will be rolling out.

**Comment by colecrawford23** [comment]
Sweet! Thank you!

**Comment by TheArrowsmith** [comment]
@colecrawford23 this is implemented now - when you go to track a recipe in your journal, the default quantities will be divided by the number of servings. Thanks!

**Comment by colecrawford23** [comment]
Speedy @TheArrowsmith! excited to give this functionality a go
