### ISSUE TITLE
Feedback on adding item

### ISSUE THREAD

**Issue by nelsonwittwer** [spoonme-kitchen/spoonme-public#6]
I made a dope veggie quesadilla for lunch. I see a lot of quesadillas in your database to choose from so I just pick one at random. I’m not sure what serving size I should pick because there isn’t a calorie preview yet. I pick 1 thinking I can update later if it feels off. In the daily dashboard view it shows my past entries with calories but I know it is off because it is only 100 calories. 

I expect to push the … button next to an entry to update serving size but it only lets me track it again or delete it.

summarizing technically:

1. Can’t edit amounts after create
2. Can’t preview calories when tracking an item.

**Comment by TheArrowsmith** [comment]
You can't currently edit a journal entry after adding it (unless it's a "custom entry" from clicking the "add custom entry" button on the search page.) This is a known limitation and we're working to fix it.

A workaround is to delete your entry and add it again. I realise this is far from ideal but we'll have an edit page ready soon!

> Can’t preview calories when tracking an item.

You mean we should give an idea of the calorie count in the search results (before clicking through to adjust/finalize the quantities)? Yes, that sounds like something we should add. I'll think about the best way to implement it.

Thanks as always for the feedback!

**Comment by migarjo** [comment]
@nelsonwittwer, I believe we have addressed both of these issues! Each food now has a calorie count preview, and foods are editable after it has been added. I'll go ahead and close this issue.
