### ISSUE TITLE
Site doesn’t fit horizontally on mini iPhone 

### ISSUE THREAD

**Issue by nelsonwittwer** [spoonme-kitchen/spoonme-public#7]
![IMG_0247](https://github.com/PeakStreak/spoonme-public/assets/758143/5fc910f5-2a2f-4cbe-937c-30ccafba55ca)

im the one person who bought a mini iPhone 12 so probably not super high priority 😂

**Comment by britton-jb** [comment]
> im the one person who bought a mini iPhone 12 so probably not super high priority 😂

As someone using the iPhone SE, there are dozens of us @nelsonwittwer

**Comment by TheArrowsmith** [comment]
I've just adjusted this to make it a bit more responsive. The Chrome developer tools tell me that this it what it now looks like on an iPhone SE:

![image](https://github.com/PeakStreak/spoonme-public/assets/85154056/ca121acf-db22-4f35-8110-eed56ebfb3d6)

I don't have an actual iPhone SE to definitively confirm, but please let me know if you still have issues on small screens! thanks

**Comment by nelsonwittwer** [comment]
Looks great!
