### ISSUE TITLE
Recipe creation - portions for raw produce

### ISSUE THREAD

**Issue by nelsonwittwer** [spoonme-kitchen/spoonme-public#8]
I’d love to see portions for onions, peppers, and I’m assuming all produce in measurements of number of items. I’d expect to specify 1 green pepper, 1 yellow, and 1 sweet pepper. 

![IMG_0249](https://github.com/PeakStreak/spoonme-public/assets/758143/c59c68fe-1c15-4036-84bd-c4f18889aebe)

**Comment by migarjo** [comment]
Thanks for bringing this up, @nelsonwittwer! We are actively working to fill in this data. Our primary source for raw ingredients is inconsistent with regard to portions. For example, bananas include portions the way you described, but bell peppers do not. We're currently working to fill in these gaps ourselves, but we're also working on a wiki-like contribution interface for ingredients where users will be able to help us to fill these gaps more quickly.

**Comment by migarjo** [comment]
@nelsonwittwer, we've been working to fill in this data and we've come a long way in the last month. The onions and bell peppers specifically should have individual units. If you see any others that need improvement, please feel free to let us know and we'll get those as well. I'll close this issue.
