### ISSUE TITLE
No button to edit recipe on show/detail view

### ISSUE THREAD

**Issue by nelsonwittwer** [spoonme-kitchen/spoonme-public#9]
![IMG_0250](https://github.com/PeakStreak/spoonme-public/assets/758143/8d256392-4e73-4977-9a51-f45f854a1dca)

I found one on the index/collection view though!

**Comment by TheArrowsmith** [comment]
Hi Nelson,

There are 'edit' and 'delete' buttons on this page, but it seems they weren't visible on narrow screens.

<img width="851" alt="image" src="https://github.com/PeakStreak/spoonme-public/assets/85154056/aaaf30c9-8308-4ce0-9498-00aa767780b0">

I've updated this so they're now also visible on mobile. Thanks for pointing this out!

George
